drop table PRODUCT if exists;

create table PRODUCT(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description varchar(200),
    PRIMARY KEY (id)
);